#!/bin/bash
[ -z "$CLUSTER" ] && CLUSTER="hadoop102 hadoop103 hadoop104"
pdsh -w "$CLUSTER" "$*" | sort -k1 | awk -F ": " '{if (host!=$1) {host=$1;print ">>>>>>>>>>>>  "host"  <<<<<<<<<<<<"};$1=null;print $0  }'
